# Algorithm Variables
COLLISION_THRESHOLD = 15
FORWARD_STEP_CM = 5
LOWER_TURN_LIMIT = 90
HIGHER_TURN_LIMIT = 180
SENSOR_THRESHOLD = 50
TURN_GRADIENT = 5

#setup Ultrasonic GPIO Pins
LEFT_GPIO_TRIGGER = 4
LEFT_GPIO_ECHO = 17
RIGHT_GPIO_TRIGGER = 27
RIGHT_GPIO_ECHO = 22
CENTER_GPIO_TRIGGER = 10
CENTER_GPIO_ECHO = 9

# GPIO Motor Pins
R_MOTOR_ACTV = 21
R_MOTOR_FW = 14
R_MOTOR_RV = 15
L_MOTOR_ACTV = 20
L_MOTOR_FW = 18
L_MOTOR_RV = 23

# Encoder Pin
R_MOTOR_ENC = 24
R_MOTOR_VAL = 25
L_MOTOR_ENC = 8
L_MOTOR_VAL = 7

# Drivetrain Constants
LR_BIAS = 0.80  # INCREASING makes the left motor go faster DECREASING makes it go slightly slower
LR_BIAS_forward = 1.05
PWM_FREQ = 100
